### ISSUE TITLE
Including data when used in code

### ISSUE THREAD

**Issue by Hannarea** [mattcrespo314/SIAM-Knights-#1]
Hey! 
*Just a suggestion*  - you may wish to add the data used in your code to this repo. This way, it is complete :)

**Comment by mattcrespo314** [comment]
Oh, I totally forgot, thank you!
Best,

Matthew Crespo
________________________________
From: Hanna Reed ***@***.***>
Sent: Tuesday, March 30, 2021 12:47 PM
To: mattcrespo314/SIAM-Knights- ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [mattcrespo314/SIAM-Knights-] Including data when used in code (#1)


Hey!
Just a suggestion - you may wish to add the data used in your code to this repo. This way, it is complete :)

**Comment by Hannarea** [comment]
No problem!
